### PR TITLE
rgw/sfs: Set the type of the default user to TYPE_RGW.

### PR DESCRIPTION
**Pull request by votdev**
Right now the type of our default user is `TYPE_NONE` which seems to be incorrect because new users that are created with the AdminOps API have the type `TYPE_RGW`. The same is when creating users via the CLI, e.g. `radosgw-admin user create --uid=dev --display-name=Developer --system` (in a SES7.1 cluster).

Signed-off-by: Volker Theile <vtheile@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by jecluis** [comment]
@votdev mind prepending the commit message with `rgw/sfs:`?

**Review by jecluis — APPROVED** [review]
lgtm, but haven't tested it. @0xavi0 can you run the smoke tests against it and see if they succeed?

**Review by 0xavi0 — APPROVED** [review]
LTGM, smoke tests pass

**Comment by jecluis** [comment]
@votdev commit needs to be signed to merge.

**Comment by votdev** [comment]
Öhm, what happened here?

**Comment by votdev** [comment]
Something went totally wrong here. I've opened a new PR, see https://github.com/aquarist-labs/ceph/pull/24.

**Pull request merged**
