### PR TITLE
Server Side Encryption Support

### LINKED ISSUE #522: rgw/sfs: Server Side Encryption: PUT GET S3 tests fail with broken data
**Describe the bug**

test_encrypted_transfer_* S3 tests report broken data. These are basic PUT then GET tests. 
Encryption / decryption is done by the RGW ops layer and mostly (modulo metadata) transparent to SFS. 
Theory: metadata lost or not available in the GET path when needed.

The radosgw logs show (using test_encrypted_transfer_1b as an example here)
 - put_obj writes out a byte 
 - put_obj sees the rgw crypto related attribute user.rgw.crypt.mode. This is used by the GET path to put in a decrypt filter.
 - get_obj successfully reads and returns the byte

PUT
```
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj normalizing buckets and tenants
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s->object=testobj s->bucket=sfstest-l1ltjggqyt3qfrcofmasr-1
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj init permissions
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj get_bucket: bucket: sfstest-l1ltjggqyt3qfrcofmasr-1
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj recalculating target
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj reading permissions
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj init op
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 get_quota: TODO
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj verifying op mask
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj verifying op permissions
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj Searching permissions for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, acct_name=youruseridhere, subuser=, perm_mask=15, is_admin=0) mask=50
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj Searching permissions for uid=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj Found permission: 15
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj Searching permissions for group=1 mask=50
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj Permissions for group not found
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj Searching permissions for group=2 mask=50
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj Permissions for group not found
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj -- Getting permissions done for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, acct_name=youruseridhere, subuser=, perm_mask=15, is_admin=0), owner=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, perm=2
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj  identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, acct_name=youruseridhere, subuser=, perm_mask=15, is_admin=0) requested perm (type)=2, policy perm=2, user_perm_mask=2, acl perm=2
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj verifying op params
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj pre-executing
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj check rate limiting
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 get_ratelimit: TODO
2023-05-16T11:15:36.855+0000 7f7195f1f700  2 req 0 0.004000073s s3:put_obj executing
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj check_quota: user(max size: -1, max objs: -1), bucket(max size: -1, max objs: -1), obj size: 1
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj check_quota: not implemented, return okay.
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj swift_versioning_copy: do nothing.
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 get_notification: return stub notification
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj get_atomic_writer: return basic atomic writer
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj > atomic_writer::SFSAtomicWriter head_obj: testobj, bucket: sfstest-l1ltjggqyt3qfrcofmasr-1
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj > atomic_writer::prepare creating file at "/data/4d/18/34bb-2752-4f86-9793-d954a16c03a9/1"
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj NOTICE: call to do_aws4_auth_completion
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj v4 auth ok -- do_aws4_auth_completion
2023-05-16T11:15:36.855+0000 7f7195f1f700 -1 load failed dlopen(): "/usr/local/lib64/ceph/crypto/libceph_crypto_isal.so: cannot open shared object file: No such file or directory" or "/usr/local/lib64/ceph/libceph_crypto_isal.so: cannot open shared object file: No such file or directory"
2023-05-16T11:15:36.855+0000 7f7195f1f700 -1 req 0 0.004000073s get_crypto_accel cannot load crypto accelerator of type crypto_isal
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj > atomic_writer::process data len: 1, offset: 0, io_failed: false, fd: 36, fn: /data/4d/18/34bb-2752-4f86-9793-d954a16c03a9/1
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj > atomic_writer::process data len: 0, offset: 1, io_failed: false, fd: 36, fn: /data/4d/18/34bb-2752-4f86-9793-d954a16c03a9/1
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj > atomic_writer::process final piece, wrote 1 bytes
2023-05-16T11:15:36.855+0000 7f7195f1f700  5 req 0 0.004000073s s3:put_obj NOTICE: call to do_aws4_auth_completion
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj check_quota: user(max size: -1, max objs: -1), bucket(max size: -1, max objs: -1), obj size: 1
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj check_quota: not implemented, return okay.
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj x>> x-amz-content-sha256:559aead08264d5795d3909718cdd05abd49572e84fe55590eef31a88a08fdffd
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj x>> x-amz-date:20230516T111536Z
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj skipping x>> x-amz-server-side-encryption-customer-algorithm
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj skipping x>> x-amz-server-side-encryption-customer-key
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj skipping x>> x-amz-server-side-encryption-customer-key-md5
2023-05-16T11:15:36.855+0000 7f7195f1f700 10 req 0 0.004000073s s3:put_obj > atomic_writer::complete accounted_size: 1, etag: 7fc56270e7a70fa81a5935b72eacbe29, set_mtime: 1970-01-01T00:00:00.000000000Z, attrs: user.rgw.acl, user.rgw.crypt.keymd5, user.rgw.crypt.mode, user.rgw.etag, user.rgw.x-amz-content-sha256, user.rgw.x-amz-date, delete_at: 1970-01-01T00:00:00.000000000Z, if_match: NA, if_nomatch: NA
2023-05-16T11:15:36.871+0000 7f7195f1f700  2 req 0 0.020000363s s3:put_obj completing
2023-05-16T11:15:36.871+0000 7f7195f1f700  2 req 0 0.020000363s s3:put_obj op status=0
2023-05-16T11:15:36.871+0000 7f7195f1f700  2 req 0 0.020000363s s3:put_obj http status=200
2023-05-16T11:15:36.871+0000 7f7195f1f700  1 ====== req done req=0x7f70cfd11740 op status=0 http_status=200 latency=0.020000363s ======
2023-05-16T11:15:36.871+0000 7f7195f1f700  1 beast: 0x7f70cfd11740: 127.0.0.1 - 

```

GET

```
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj normalizing buckets and tenants
2023-05-16T11:15:36.871+0000 7f719371a700 10 req 0 0.000000000s s->object=testobj s->bucket=sfstest-l1ltjggqyt3qfrcofmasr-1
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj init permissions
2023-05-16T11:15:36.871+0000 7f719371a700 10 req 0 0.000000000s s3:get_obj get_bucket: bucket: sfstest-l1ltjggqyt3qfrcofmasr-1
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj recalculating target
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj reading permissions
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj init op
2023-05-16T11:15:36.871+0000 7f719371a700 10 get_quota: TODO
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj verifying op mask
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj verifying op permissions
2023-05-16T11:15:36.871+0000 7f719371a700  5 req 0 0.000000000s s3:get_obj Searching permissions for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, acct_name=youruseridhere, subuser=, perm_mask=15, is_admin=0) mask=49
2023-05-16T11:15:36.871+0000 7f719371a700  5 req 0 0.000000000s s3:get_obj Searching permissions for uid=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
2023-05-16T11:15:36.871+0000 7f719371a700  5 req 0 0.000000000s s3:get_obj Found permission: 15
2023-05-16T11:15:36.871+0000 7f719371a700  5 req 0 0.000000000s s3:get_obj Searching permissions for group=1 mask=49
2023-05-16T11:15:36.871+0000 7f719371a700  5 req 0 0.000000000s s3:get_obj Permissions for group not found
2023-05-16T11:15:36.871+0000 7f719371a700  5 req 0 0.000000000s s3:get_obj Searching permissions for group=2 mask=49
2023-05-16T11:15:36.871+0000 7f719371a700  5 req 0 0.000000000s s3:get_obj Permissions for group not found
2023-05-16T11:15:36.871+0000 7f719371a700  5 req 0 0.000000000s s3:get_obj -- Getting permissions done for identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, acct_name=youruseridhere, subuser=, perm_mask=15, is_admin=0), owner=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, perm=1
2023-05-16T11:15:36.871+0000 7f719371a700 10 req 0 0.000000000s s3:get_obj  identity=rgw::auth::SysReqApplier -> rgw::auth::LocalApplier(acct_user=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef, acct_name=youruseridhere, subuser=, perm_mask=15, is_admin=0) requested perm (type)=1, policy perm=1, user_perm_mask=15, acl perm=1
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj verifying op params
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj pre-executing
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj check rate limiting
2023-05-16T11:15:36.871+0000 7f719371a700 10 get_ratelimit: TODO
2023-05-16T11:15:36.871+0000 7f719371a700  2 req 0 0.000000000s s3:get_obj executing
2023-05-16T11:15:36.875+0000 7f719371a700 10 req 0 0.004000073s s3:get_obj > object_read::prepare bucket: sfstest-l1ltjggqyt3qfrcofmasr-1, obj: testobj, size: 1
2023-05-16T11:15:36.875+0000 7f719371a700 10 req 0 0.004000073s s3:get_obj > object_read::iterate bucket: sfstest-l1ltjggqyt3qfrcofmasr-1, obj: testobj, size: 1, offset: 0, end: 0, len: 1
2023-05-16T11:15:36.875+0000 7f719371a700 10 req 0 0.004000073s s3:get_obj > object_read::iterate return 1/1, offset: 0, missing: 0
2023-05-16T11:15:36.875+0000 7f718a708700  2 req 0 0.004000073s s3:get_obj completing
2023-05-16T11:15:36.875+0000 7f718a708700  2 req 0 0.004000073s s3:get_obj op status=0
2023-05-16T11:15:36.875+0000 7f718a708700  2 req 0 0.004000073s s3:get_obj http status=200
```

### PR DESCRIPTION
**Pull request by irq0**
SSE support for regular PUTs and multipart uploads.

Server-side encrypted objects requires writers to store a manifest in
user.rgw.manifest attribute to tell the decryptor about chunk
boundaries.

With regular PUTs, the whole upload is a chunk.
With multipart uploads, each part is a separate chunk.

Fixes: https://github.com/aquarist-labs/s3gw/issues/522
Epic: https://github.com/aquarist-labs/s3gw/issues/564

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

### CODE REVIEW

**Comment by irq0** [comment]
Dependencies:
- https://github.com/aquarist-labs/s3gw/issues/521
- SSE KMS options in the s3 test runner

**Comment by irq0** [comment]
Dependencies:
- https://github.com/aquarist-labs/s3gw/issues/521
- SSE KMS options in the s3 test runner

**Comment by irq0** [comment]
Tests fail because the s3test runner doesn't pass on a param to rgw correctly. On hold till we have s3tr in the pipeline

**Review by 0xavi0 — APPROVED** [review]
LG2M

**Pull request merged**
