### PR TITLE
Conditional GETs

### LINKED ISSUE #523: rgw/sfs: GET Conditionals If-* / Handle ReadOp::Params if_(no)match (un)mod_ptr
S3 GET may be conditional. We currently don't handle the following conditionals:

> From [S3 GetObject params](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#:~:text=checksum%2Dmode%3A%20ChecksumMode-,URI%20Request%20Parameters,-The%20request%20uses)
https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html
> If-Match
> Return the object only if its entity tag (ETag) is the same as the one specified; otherwise, return a 412 (precondition failed) error.
> If-Modified-Since
> Return the object only if it has been modified since the specified time; otherwise, return a 304 (not modified) error.
> If-None-Match
> Return the object only if its entity tag (ETag) is different from the one specified; otherwise, return a 304 (not modified) error.
> If-Unmodified-Since
> Return the object only if it has not been modified since the specified time; otherwise, return a 412 (precondition failed) error.

In the SAL layer this corresponds to ReadOp::Params: 
- if_(no)match == If-Match, If-None-Match
- (un)mod_ptr == If-Modified-Since, If-Unmodified-Since

## Tests

with postfixes 'good' and 'failed':
test_get_object_ifmatch_
test_get_object_ifmodifiedsince_
test_get_object_ifnonematch_
test_get_object_ifunmodifiedsince_

## Additional context 
[S3 GetObject params](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#:~:text=checksum%2Dmode%3A%20ChecksumMode-,URI%20Request%20Parameters,-The%20request%20uses)
https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html

### PR DESCRIPTION
**Pull request by irq0**
Add conditional GET support.

Fixes: https://github.com/aquarist-labs/s3gw/issues/523

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

### CODE REVIEW

**Review by 0xavi0 — COMMENTED** [review]
Looks good to me but I have one question:

I see the following in the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html):

**Overriding Response Header _Values** 
If both of the If-Match and If-Unmodified-Since headers are present in the request as follows: If-Match condition evaluates to true, and; If-Unmodified-Since condition evaluates to false; then, S3 returns 200 OK and the data requested.

If both of the If-None-Match and If-Modified-Since headers are present in the request as follows: If-None-Match condition evaluates to false, and; If-Modified-Since condition evaluates to true; then, S3 returns 304 Not Modified response code.



Should we also implement those cases?

**Comment by irq0** [comment]
> Looks good to me but I have one question:
> 
> I see the following in the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html):
> 
> **Overriding Response Header _Values** If both of the If-Match and If-Unmodified-Since headers are present in the request as follows: If-Match condition evaluates to true, and; If-Unmodified-Since condition evaluates to false; then, S3 returns 200 OK and the data requested.
> 
> If both of the If-None-Match and If-Modified-Since headers are present in the request as follows: If-None-Match condition evaluates to false, and; If-Modified-Since condition evaluates to true; then, S3 returns 304 Not Modified response code.
> 
> Should we also implement those cases?

I read the MDN docs.. They only have the first combination. 

Last push adds the second and the relevant RFC sections in the comments.

**Comment by 0xavi0** [comment]
This is a bit confusing... 
According to the Amazon docs `If-Modified-Since` should only be ignored when `If-None-Match` evaluates to `false`.

---
If both of the If-None-Match and If-Modified-Since headers are present in the request as follows: If-None-Match condition evaluates to false, and; If-Modified-Since condition evaluates to true; then, S3 returns 304 Not Modified response code.
---

But, Amazon docs points to RFC 7232, which says to ignore `If-Modified-Since` always when `If-None-Match`  is present.

---
   A recipient MUST ignore If-Modified-Since if the request contains an
   If-None-Match header field; the condition in If-None-Match is
   considered to be a more accurate replacement for the condition in
   If-Modified-Since, and the two are only combined for the sake of
   interoperating with older intermediaries that might not implement
   If-None-Match.
---

The actual implementation is done following RFC 7232.
If `If-None-Match` and `If-Modified-Since`  are present and `If-None-Match` evaluates to `true` and `If-Modified-Since` evaluates to `false` we're returning 0 because the latter is ignored.

I wonder if that's inline with the Amazon docs.... because they only mention to ignore when `If-None-Match` evaluates to `false`.

The question would be: is Amazon following RFC 7232 and the docs are confusing or are they following a modified version of RFC 7232?

**Review by 0xavi0 — APPROVED** [review]
Approving. 
We're considering Amazon docs not very accurate and we're following RFC 7232.

**Pull request merged**
