### PR TITLE
Add s3gw specfile, systemd service and sysconfig file

### PR DESCRIPTION
**Pull request by tserong**
This commit adds an s3gw.spec file for building a standalone s3gw RPM, along with a systemd unit file and sysconfig file to tweak settings (e.g. local data directory).  The systemd unit file and sysconfig file are not necessary or even desirable when running containerized, but make sense in the context of a standalone package.

s3gw.spec is based on the existing ceph.spec.in, but instead of creating a ceph package plus a bunch of library packages and other subpackages, s3gw.spec creates a single RPM containing the radosgw binary, librados, libradosgw and libceph-common.  The s3gw RPM is set to conflict with ceph-radosgw and librados2, to avoid accidental installation alongside (or on top of!) a regular ceph deployment.

With this, we can do package builds on OBS with pretty much nothing other than a _service file, as can be currently seen at https://build.opensuse.org/package/show/home:tserong:branches:filesystems:ceph:s3gw/s3gw

```
<?xml version="1.0"?>
<services>
  <service name="obs_scm">
    <param name="versionformat">0.7.0.@PARENT_TAG@.@TAG_OFFSET@</param>
    <param name="url">https://github.com/tserong/ceph.git</param>
    <param name="scm">git</param>
    <param name="revision">s3gw-obs-automation-experiment</param>
    <param name="extract">s3gw.spec</param>
    <param name="changesgenerate">enable</param>
  </service>
  <service name="set_version"/>
  <service name="tar" mode="buildtime"/>
</services>
```

Given the above, OBS will go grab the source from github, extract s3gw.spec, plug in a somewhat sensible version number, generate a somewhat useful changelog and build an RPM for us.

Note:

- The primary purpose of this work is to enable automatic builds on build.opensuse.org.  That's why the version in the spec file is set to "WILL_BE_OVERWRITTEN_BY_OBS".
- There are some SUSE-isms in the spec file, especially in the %pre and %post scripts.  This will need adjusting if we want to try Fedora/RH builds.
- s3gw is configured to use system boost, with necessary build dependencies available from filesystems:ceph:s3gw on OBS.
- I've switched to using ninja instead of make for the build, because I couldn't get make to only build radsogw and deps.
- I've set -DENABLE_GIT_VERSION=OFF, because this allows us to do builds straight from a git checkout, without needing to generate a source tarball with `make-dist`.
- There may be other cmake flags that we can still turn off, or other things that can be stripped back further.

Fixes: https://github.com/aquarist-labs/s3gw/issues/154
Signed-off-by: Tim Serong <tserong@suse.com>

### CODE REVIEW

**Comment by tserong** [comment]
Note to reviewers: you'll find `diff -u ceph.spec.in s3gw.spec` or - even better - `meld ceph.spec.in s3gw.spec` much nicer than trying to read and make sense of the new spec file in isolation.

**Review by jecluis — APPROVED** [review]

**Comment by jecluis** [comment]
@tserong commits need to be signed, otherwise looks good to me.

**Comment by tserong** [comment]
> @tserong commits need to be signed, otherwise looks good to me.

@jecluis I assume you mean it needed a GPG signature, and, no problem, done. Is that requirement documented somewhere?

**Comment by jecluis** [comment]
> > @tserong commits need to be signed, otherwise looks good to me.
> 
> @jecluis I assume you mean it needed a GPG signature, and, no problem, done. Is that requirement documented somewhere?

Unsure. Probably not documented. Should go into the contributing guidelines for s3gw I suppose. I don't think this is a requirement for Ceph's upstream repo.

**Comment by jecluis** [comment]
build is failing on the compress stage
```
Run tar -czvf build-results.tar.gz \
  tar -czvf build-results.tar.gz \
    ceph/build/bin/radosgw \
    ceph/build/bin/unittest_rgw_sfs_sqlite_users \
    ceph/build/bin/unittest_rgw_sfs_sqlite_buckets \
    ceph/build/bin/unittest_rgw_sfs_sqlite_objects \
    ceph/build/bin/unittest_rgw_sfs_sqlite_versioned_objects \
    ceph/build/bin/unittest_rgw_sfs_sfs_bucket \
    ceph/build/bin/unittest_rgw_sfs_metadata_compatibility \
    ceph/build/bin/unittest_rgw_sfs_gc \
    ceph/build/lib/libceph-common.so \
    ceph/build/lib/libceph-common.so.[2](https://github.com/aquarist-labs/ceph/actions/runs/3672091186/jobs/6207942218#step:6:2) \
    ceph/build/lib/libradosgw.so \
    ceph/build/lib/libradosgw.so.2 \
    ceph/build/lib/libradosgw.so.2.0.0 \
    ceph/build/lib/librados.so \
    ceph/build/lib/librados.so.2 \
    ceph/build/lib/librados.so.2.0.0
  shell: /usr/bin/bash -e {0}
tar: ceph/build/bin/radosgw: Cannot stat: No such file or directory
ceph/build/bin/unittest_rgw_sfs_sqlite_users
ceph/build/bin/unittest_rgw_sfs_sqlite_buckets
ceph/build/bin/unittest_rgw_sfs_sqlite_objects
ceph/build/bin/unittest_rgw_sfs_sqlite_versioned_objects
ceph/build/bin/unittest_rgw_sfs_sfs_bucket
ceph/build/bin/unittest_rgw_sfs_metadata_compatibility
ceph/build/bin/unittest_rgw_sfs_gc
ceph/build/lib/libceph-common.so
ceph/build/lib/libceph-common.so.2
ceph/build/lib/libradosgw.so
ceph/build/lib/libradosgw.so.2
ceph/build/lib/libradosgw.so.2.0.0
ceph/build/lib/librados.so
ceph/build/lib/librados.so.2
ceph/build/lib/librados.so.2.0.0
tar: Exiting with failure status due to previous errors
Error: Process completed with exit code 2.
```

I'm not sure whether this is due to this PR's things or the github action that is borked.

**Comment by tserong** [comment]
The build failure shouldn't be due to this commit, as nothing in here actually gets built ;-)

**Comment by jecluis** [comment]
Yeah, makes sense. @m-ildefons any clue what may be causing this?

**Comment by tserong** [comment]
> Unsure. Probably not documented. Should go into the contributing guidelines for s3gw I suppose. I don't think this is a requirement for Ceph's upstream repo.

Ah... It _was_ in s3gw's docs/contributing.md, but not in CONTRIBUTING.md, so I've opened https://github.com/aquarist-labs/s3gw/pull/268 to take care of that.

**Comment by m-ildefons** [comment]
Looks to me like the compress stage expects unit tests to be built, but they aren't in this case.

**Comment by jecluis** [comment]
> Looks to me like the compress stage expects unit tests to be built, but they aren't in this case.

But this PR itself is not doing anything to the build. What could possibly cause these not to be built? This certainly comes from the base branch.

**Comment by jecluis** [comment]
See https://github.com/aquarist-labs/ceph/actions/runs/3666623525/jobs/6198484646 also failed on the same place.

**Comment by jecluis** [comment]
@m-ildefons  I suspect it might have been https://github.com/aquarist-labs/s3gw-tools/pull/198/files that changed the behavior.

**Review by jecluis — APPROVED** [review]

**Pull request merged**
