### PR TITLE
rgw/sfs: Fixed bucket creation time always set at now() for SFS backend

### PR DESCRIPTION
**Pull request by giubacc**
Creation time for buckets was correctly set on sqlite table but
when retrieving it, the data was not propagated during the object
copy chain.

Tested using s3cmd.

Fixes: https://github.com/aquarist-labs/s3gw/issues/63
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by votdev — APPROVED** [review]

**Review by jecluis — APPROVED** [review]

**Review by jecluis — CHANGES_REQUESTED** [review]
this should be two logical commits instead of one: first one changing the workflow, a subsequent commit to fix the bug.

**Comment by giubacc** [comment]
> this should be two logical commits instead of one: first one changing the workflow, a subsequent commit to fix the bug.

restored commits as were just before the squashing

**Review by 0xavi0 — APPROVED** [review]
lgtm

**Review by jecluis — CHANGES_REQUESTED** [review]
@giubacc both commits have the same message but are doing different things. Also, please prepend them with the component they are changing (i.e., `rgw/sfs`).

**Comment by giubacc** [comment]
> @giubacc both commits have the same message but are doing different things. Also, please prepend them with the component they are changing (i.e., `rgw/sfs`).

please, check now

**Review by jecluis — APPROVED** [review]

**Review by votdev — APPROVED** [review]

**Pull request merged**
