### PR TITLE
rgw/sfs: include sqlite_orm v1.7.1 as submodule

### LINKED ISSUE #683: Submodule in sqlite_orm
### What needs to be done

Add sqlite_orm as a submodule. Make cmake use that submodule rather than a system-wide installed version.

Remove our custom package and change the build jobs that pull it in.

### Why it needs to be done

sqlite_orm is a header only library. Right now we only have x86_64 packages. Submodule would enable arm builds right away

We may want to add custom patches on top. sqlite extended error codes come to mind.

Now and them we have build failures when pulling the packages from the repo

### PR DESCRIPTION
**Pull request by tserong**
Given sqlite_orm is a header only library it doesn't actually need to be built  - we just need to get it added to the system include directories.

Fixes: https://github.com/aquarist-labs/s3gw/issues/683

### CODE REVIEW

**Comment by tserong** [comment]
A couple of notes:
- I tried v1.8.2, but that gave a bunch of "‘sqlite_orm::internal::autoincrement_t sqlite_orm::autoincrement()’ is deprecated: Use primary_key().autoincrement()` instead" errors, so to use v1.8.2, I'd also need to update dbconn.h to fix these. Given that I figure it's safer to first get v1.7.1 in (which we already build against), the do the v1.8.2 update separately.
- This will also need a change to the Dockerfiles in the main s3gw repo to get rid of libsqliteorm, but this change has to go in first.

**Comment by tserong** [comment]
Actually v1.8.2 doesn't seem too painful - I'm testing that separately in https://github.com/aquarist-labs/ceph/pull/209/commits/dbff419803e1b44559b3bc3b3718321863806fc7 - but I would still prefer to merge this PR first, and do the v1.8.2 update in a separate standalone PR, just for the sake of clarity.

**Review by jecluis — APPROVED** [review]
lgtm

**Comment by tserong** [comment]
(force pushed to gpg sign commit)

**Pull request merged**
