### PR TITLE
test_expiration() removed from test-sfs-lifecycle-smoke.py

### PR DESCRIPTION
**Pull request by sdemiraj**
This test case was removed.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

### CODE REVIEW

**Comment by jecluis** [comment]
@sdemiraj The commit needs to have a valid DCO. Additionally, I'd ask for the commit title to be below 60 characters. I'd recommend to cut the current title just before "because", and add an explanation proper to the commit body message.

**Review by jecluis — CHANGES_REQUESTED** [review]
commit requires DCO and a shorter title.

**Review by m-ildefons — CHANGES_REQUESTED** [review]
Don't reference the location of the code in the s3tests repo with a line number, as that will change when people add/remove code there over time. Just the name of the test this overlaps with is fine.
Also please reference the GitHub issue that this change is related to, at least in the PR message, better in the commit itself.
The code change itself looks good to me.

**Comment by 0xavi0** [comment]
I would say we can safely delete this whole file in favour of the `s3tests`

**Comment by asettle** [comment]
> I would say we can safely delete this whole file in favour of the `s3tests`

@sdemiraj what do you think? @m-ildefons

**Comment by jhmarina** [comment]
Closing this PR as Sid's internship is officially finished

**Pull request closed without merging**
